CREATE INDEX `idx_dr_speciality_provideruuid` ON `tbl_dr_speciality` (`provideruuid`);--> statement-breakpoint
CREATE INDEX `idx_dr_speciality_attributetypeuuid` ON `tbl_dr_speciality` (`attributetypeuuid`);--> statement-breakpoint
CREATE INDEX `idx_encounter_visituuid` ON `tbl_encounter` (`visituuid`);--> statement-breakpoint
CREATE INDEX `idx_encounter_provider_uuid` ON `tbl_encounter` (`provider_uuid`);--> statement-breakpoint
CREATE INDEX `idx_encounter_encounter_type_uuid` ON `tbl_encounter` (`encounter_type_uuid`);--> statement-breakpoint
CREATE INDEX `idx_encounter_sync` ON `tbl_encounter` (`sync`);--> statement-breakpoint
CREATE INDEX `idx_image_records_patientuuid` ON `tbl_image_records` (`patientuuid`);--> statement-breakpoint
CREATE INDEX `idx_image_records_visituuid` ON `tbl_image_records` (`visituuid`);--> statement-breakpoint
CREATE INDEX `idx_image_records_encounteruuid` ON `tbl_image_records` (`encounteruuid`);--> statement-breakpoint
CREATE INDEX `idx_image_records_sync` ON `tbl_image_records` (`sync`);--> statement-breakpoint
CREATE INDEX `idx_location_sync` ON `tbl_location` (`sync`);--> statement-breakpoint
CREATE INDEX `idx_obs_encounteruuid` ON `tbl_obs` (`encounteruuid`);--> statement-breakpoint
CREATE INDEX `idx_obs_conceptuuid` ON `tbl_obs` (`conceptuuid`);--> statement-breakpoint
CREATE INDEX `idx_obs_creatoruuid` ON `tbl_obs` (`creatoruuid`);--> statement-breakpoint
CREATE INDEX `idx_obs_sync` ON `tbl_obs` (`sync`);--> statement-breakpoint
CREATE INDEX `idx_patient_creatoruuid` ON `tbl_patient` (`creatoruuid`);--> statement-breakpoint
CREATE INDEX `idx_patient_sync` ON `tbl_patient` (`sync`);--> statement-breakpoint
CREATE INDEX `idx_patient_attribute_patientuuid` ON `tbl_patient_attribute` (`patientuuid`);--> statement-breakpoint
CREATE INDEX `idx_patient_attribute_person_attribute_type_uuid` ON `tbl_patient_attribute` (`person_attribute_type_uuid`);--> statement-breakpoint
CREATE INDEX `idx_patient_attribute_sync` ON `tbl_patient_attribute` (`sync`);--> statement-breakpoint
CREATE INDEX `idx_patient_attribute_master_sync` ON `tbl_patient_attribute_master` (`sync`);--> statement-breakpoint
CREATE INDEX `idx_provider_useruuid` ON `tbl_provider` (`useruuid`);--> statement-breakpoint
CREATE INDEX `idx_provider_sync` ON `tbl_provider` (`sync`);--> statement-breakpoint
CREATE INDEX `idx_provider_attribute_provideruuid` ON `tbl_provider_attribute` (`provideruuid`);--> statement-breakpoint
CREATE INDEX `idx_provider_attribute_attributetypeuuid` ON `tbl_provider_attribute` (`attributetypeuuid`);--> statement-breakpoint
CREATE INDEX `idx_rtc_connection_log_visit_uuid` ON `tbl_rtc_connection_log` (`visit_uuid`);--> statement-breakpoint
CREATE INDEX `idx_user_credentials_creator_uuid_cred` ON `tbl_user_credentials` (`creator_uuid_cred`);--> statement-breakpoint
CREATE INDEX `idx_user_credentials_provider_uuid_cred` ON `tbl_user_credentials` (`provider_uuid_cred`);--> statement-breakpoint
CREATE INDEX `idx_visit_patientuuid` ON `tbl_visit` (`patientuuid`);--> statement-breakpoint
CREATE INDEX `idx_visit_visit_type_uuid` ON `tbl_visit` (`visit_type_uuid`);--> statement-breakpoint
CREATE INDEX `idx_visit_locationuuid` ON `tbl_visit` (`locationuuid`);--> statement-breakpoint
CREATE INDEX `idx_visit_sync` ON `tbl_visit` (`sync`);--> statement-breakpoint
CREATE INDEX `idx_visit_attribute_visit_uuid` ON `tbl_visit_attribute` (`visit_uuid`);--> statement-breakpoint
CREATE INDEX `idx_visit_attribute_visit_attribute_type_uuid` ON `tbl_visit_attribute` (`visit_attribute_type_uuid`);--> statement-breakpoint
CREATE INDEX `idx_visit_attribute_sync` ON `tbl_visit_attribute` (`sync`);